### ISSUE TITLE
Add npm binary

### ISSUE THREAD

**Issue by XhmikosR** [Venemo/css-fitness#2]

**Comment by Venemo** [comment]
@XhmikosR This is something I'm planning to do but don't exactly know how to. Can you give me some pointers about it?

**Comment by XhmikosR** [comment]
The easy part is to add the package.json info.

``` json
{
  "bin": {
    "cssfitness": "./css-fitness.js"
  }
}
```

But you will need something like commander for the cli so maybe you should have a look at how clean-css does it.
